### ISSUE TITLE
请问能支持jakarta吗

### ISSUE THREAD

**Issue by shuigedeng** [houbb/validator#1]

**Comment by houbb** [comment]
JSR 标准都是可以的，常见的都支持的。后续会扩充些。

> [支持的约束注解](https://github.com/houbb/validator#%E6%B3%A8%E8%A7%A3%E8%AF%B4%E6%98%8E)

**Comment by houbb** [comment]
V0.5.0 已支持 3.0 标准所有内置注解。

> [ jakarta bean validation 约束注解支持](https://github.com/houbb/validator#jsr-303--jakarta-bean-validation-%E7%BA%A6%E6%9D%9F%E6%B3%A8%E8%A7%A3%E6%94%AF%E6%8C%81)
